// Package discovery walks the filesystem, detects version-bearing files, and
// generates an incrmit configuration.
package discovery

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/sasmaq/incrmit/internal/config"
	"github.com/sasmaq/incrmit/internal/version"
)

// Result is a single discovered target: a path relative to the scan root and
// the semantic version detected inside it.
type Result struct {
	Path    string
	Version version.Version
}

// ignoredDirs are directory names skipped during the walk: version-control
// metadata, dependency caches, and common build outputs.
var ignoredDirs = map[string]struct{}{
	".git":         {},
	".hg":          {},
	".svn":         {},
	"node_modules": {},
	"vendor":       {},
	"dist":         {},
	"build":        {},
	"target":       {},
}

// goVersionRe matches a Go `const Version = "x.y.z"` declaration (the `const`
// keyword is optional so it also matches entries inside a const block).
var goVersionRe = regexp.MustCompile(`(?m)^\s*(?:const\s+)?Version\s*=\s*"(\d+\.\d+\.\d+)"`)

// Discover walks the tree rooted at root and returns every target it can
// extract a semantic version from, sorted by path for deterministic output.
func Discover(root string) ([]Result, error) {
	var results []Result

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != root {
				if _, skip := ignoredDirs[d.Name()]; skip {
					return filepath.SkipDir
				}
			}
			return nil
		}

		v, ok := detect(path, d.Name())
		if !ok {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			rel = path
		}
		results = append(results, Result{Path: filepath.ToSlash(rel), Version: v})
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Slice(results, func(i, j int) bool { return results[i].Path < results[j].Path })
	return results, nil
}

// Generate renders the discovered results as the contents of an incrmit.toml
// config file, including the version detected for each target.
func Generate(results []Result) ([]byte, error) {
	cfg := config.Config{Files: make([]config.FileEntry, 0, len(results))}
	for _, r := range results {
		cfg.Files = append(cfg.Files, config.FileEntry{
			Path:    r.Path,
			Version: r.Version.String(),
		})
	}

	var buf bytes.Buffer
	buf.WriteString("# incrmit.toml (generated by `incrmit discover`)\n\n")
	if err := toml.NewEncoder(&buf).Encode(cfg); err != nil {
		return nil, fmt.Errorf("discovery: encoding config: %w", err)
	}
	return buf.Bytes(), nil
}

// detect dispatches to a format-specific extractor based on the file name. It
// is best-effort: unreadable or malformed files simply yield ok == false.
func detect(path, name string) (version.Version, bool) {
	switch {
	case name == "VERSION":
		return detectPlain(path)
	case name == "package.json":
		return detectPackageJSON(path)
	case name == "pyproject.toml":
		return detectPyproject(path)
	case name == "Cargo.toml":
		return detectCargo(path)
	case strings.HasSuffix(name, ".go"):
		return detectGoSource(path)
	default:
		return version.Version{}, false
	}
}

func detectPlain(path string) (version.Version, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return version.Version{}, false
	}
	v, err := version.Parse(strings.TrimSpace(string(data)))
	if err != nil {
		return version.Version{}, false
	}
	return v, true
}

func detectPackageJSON(path string) (version.Version, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return version.Version{}, false
	}
	var pkg struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return version.Version{}, false
	}
	return parseField(pkg.Version)
}

func detectPyproject(path string) (version.Version, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return version.Version{}, false
	}
	var doc struct {
		Project struct {
			Version string `toml:"version"`
		} `toml:"project"`
		Tool struct {
			Poetry struct {
				Version string `toml:"version"`
			} `toml:"poetry"`
		} `toml:"tool"`
	}
	if err := toml.Unmarshal(data, &doc); err != nil {
		return version.Version{}, false
	}
	if doc.Project.Version != "" {
		return parseField(doc.Project.Version)
	}
	return parseField(doc.Tool.Poetry.Version)
}

func detectCargo(path string) (version.Version, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return version.Version{}, false
	}
	var doc struct {
		Package struct {
			Version string `toml:"version"`
		} `toml:"package"`
	}
	if err := toml.Unmarshal(data, &doc); err != nil {
		return version.Version{}, false
	}
	return parseField(doc.Package.Version)
}

func detectGoSource(path string) (version.Version, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return version.Version{}, false
	}
	m := goVersionRe.FindSubmatch(data)
	if m == nil {
		return version.Version{}, false
	}
	return parseField(string(m[1]))
}

// parseField parses a version string extracted from a structured field,
// returning ok == false when the field is empty or not a valid version.
func parseField(s string) (version.Version, bool) {
	if s == "" {
		return version.Version{}, false
	}
	v, err := version.Parse(s)
	if err != nil {
		return version.Version{}, false
	}
	return v, true
}
