// Package discovery walks the filesystem, detects version-bearing files, and
// generates an incrmit configuration.
package discovery

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"

	"github.com/BurntSushi/toml"

	"github.com/sasmaq/incrmit/internal/config"
	"github.com/sasmaq/incrmit/internal/version"
)

// Result is a single discovered target: a path relative to the scan root and
// the semantic version detected inside it.
type Result struct {
	Path    string
	Version version.Version
}

// ignoredDirs are directory names skipped during the walk: version-control
// metadata, dependency caches, and common build outputs.
var ignoredDirs = map[string]struct{}{
	".git":         {},
	".hg":          {},
	".svn":         {},
	"node_modules": {},
	"vendor":       {},
	"dist":         {},
	"build":        {},
	"target":       {},
}

// versionRe matches a run of two or more dot-separated integer groups,
// optionally prefixed by a single leading "v" or "V", bounded by non-word
// characters. It deliberately matches more than just MAJOR.MINOR.PATCH: a
// candidate is validated with version.Parse, which accepts only exactly three
// components. Matching the whole dotted run (greedily) is what lets an IPv4
// address such as 192.168.1.1 be seen as a single four-component token and
// rejected, rather than having 192.168.1 (or 168.1.1) pulled out of it. The
// leading \b before the optional [vV] keeps the prefix from being taken out of
// the middle of a word (so "rev1.2.3"/"dev1.2.3" are not treated as versions).
var versionRe = regexp.MustCompile(`\b[vV]?\d+(?:\.\d+)+\b`)

// Discover walks the tree rooted at root and returns every file that contains a
// semantic version token, sorted by path for deterministic output. It scans the
// contents of any text file rather than relying on file names: the first
// MAJOR.MINOR.PATCH token found in a file is recorded as that file's version.
func Discover(root string) ([]Result, error) {
	var results []Result

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != root {
				if _, skip := ignoredDirs[d.Name()]; skip {
					return filepath.SkipDir
				}
			}
			return nil
		}

		// Never treat the config file itself as a discovered target.
		if d.Name() == config.DefaultPath {
			return nil
		}

		v, ok := detect(path)
		if !ok {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			rel = path
		}
		results = append(results, Result{Path: filepath.ToSlash(rel), Version: v})
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Slice(results, func(i, j int) bool { return results[i].Path < results[j].Path })
	return results, nil
}

// Generate renders the discovered results as the contents of an incrmit.toml
// config file, including the version detected for each target.
func Generate(results []Result) ([]byte, error) {
	cfg := config.Config{Files: make([]config.FileEntry, 0, len(results))}
	for _, r := range results {
		cfg.Files = append(cfg.Files, config.FileEntry{
			Path:    r.Path,
			Version: r.Version.String(),
		})
	}

	var buf bytes.Buffer
	buf.WriteString("# incrmit.toml (generated by `incrmit discover`)\n\n")
	if err := toml.NewEncoder(&buf).Encode(cfg); err != nil {
		return nil, fmt.Errorf("discovery: encoding config: %w", err)
	}
	return buf.Bytes(), nil
}

// detect reads the file at path and returns the first [v]MAJOR.MINOR.PATCH token
// it contains. It is best-effort: unreadable and binary files yield ok == false.
// versionRe also matches dotted-number runs that are not versions (two-component
// numbers like 3.9, four-octet IPv4 addresses like 192.168.1.1, ...); those fail
// version.Parse and are skipped, so the first token that parses as a real
// three-component version wins.
func detect(path string) (version.Version, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return version.Version{}, false
	}
	if isBinary(data) {
		return version.Version{}, false
	}
	for _, m := range versionRe.FindAll(data, -1) {
		if v, err := version.Parse(string(m)); err == nil {
			return v, true
		}
	}
	return version.Version{}, false
}

// isBinary reports whether data looks like a binary (non-text) file. A NUL byte
// is a reliable signal that a file is not human-readable text, so such files are
// skipped to avoid matching version-like byte sequences in binaries.
func isBinary(data []byte) bool {
	return bytes.IndexByte(data, 0) >= 0
}
